development:
  adapter: postgresql
  encoding: unicode
  database: myflix_dev
  pool: 5
  username: RbyWoo 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: RbyWoo
  password: 